### ISSUE TITLE
License question

### ISSUE THREAD

**Issue by IzzySoft** [jroddev/android-oss-release-tracker#1]
Could you please specify what license your app comes under?

**Comment by jroddev** [comment]
Hey @IzzySoft thanks for prompting about licensing.
I have just added an MIT License to the project [here](https://github.com/jroddev/android-oss-release-tracker/blob/master/LICENSE)
I have also included a scan of its dependency licenses [here](https://github.com/jroddev/android-oss-release-tracker/blob/master/app/src/main/assets/open_source_licenses.html)
The 2 licenses in use by dependencies are Apache 2.0 and MIT.

**Comment by IzzySoft** [comment]
Thanks for your swift response and action! Great choice. This enabled me to add your app to my repo: it will [show up here](https://apt.izzysoft.de/fdroid/index/apk/com.jroddev.android_oss_release_tracker) with the next sync around 7 pm UTC. Be welcome to [pick a badge](https://gitlab.com/IzzyOnDroid/repo/#if-my-app-is-available-here-do-you-have-a-badge-i-can-use-to-link-to-it) if you want to link there from your Readme :smiley:

Btw: looks like your app would be eligible for listing in [F-Droid](https://f-droid.org/)s own repo, which has a bit stricter inclusion criteria than mine – but therefore also a higher reputation. F-Droid builds apps from their sources (other than my repo, which picks the APKs you provide). If you're interested in that let me know and I can help you with that.

Same if you wish to be in control of how your app is presented (description, screenshots etc) – I can send you what I've set up as PR in [Fastlane](https://gitlab.com/-/snippets/1895688) format, so you can maintain that with your app here directly in your repo (my updater then would pick up changes along with APK updates). F-Droid would ask for that anyway :smile:

**Comment by jroddev** [comment]
@IzzySoft thanks for the interest in my app and the inclusion in your repo.
I hadn't heard of Fastlane before but your link was very helpful. Feel free to open a PR for adding it and I'll take a look.
I may even incorporate Fastlane into my parser as it looks like a good fallback for finding the app icon.

One issue I noticed on the listing page is these are incorrect
```
    Target: 14.0
    MinVer: 11.0
```
should be
```
    Target: 33.0
    MinVer: 29.0
```

**Comment by IzzySoft** [comment]
> Feel free to open a PR for adding it and I'll take a look.

Will do!

> One issue I noticed on the listing page is these are incorrect

No, you're misinterpreting it. Remember those details are intended for end-users, so the values are **Android** Versions and not sdkVer's. sdkVer 29 = Android 11. sdkVer 33 = Android 14.
