### ISSUE TITLE
Unable to add kiwi browser's src.next repo

### ISSUE THREAD

**Issue by LovecraftianGodsKiller** [jroddev/android-oss-release-tracker#13]
Trying to add https://github.com/kiwibrowser/src.next shows not found error. I don't know what the problem is and I'm wondering if there is something about that specific repo that prevents it from being added to the list

**Comment by jroddev** [comment]
@LovecraftianGodsKiller looks like Kiwi Browsers uses a very different repo/app structure than the standard Android (or even Flutter application). It doesn't make sense to add code to specifically parse KiwiBrowser, but when I get around to implementing https://github.com/jroddev/android-oss-release-tracker/issues/18 it will be possible to set all the required values manually.
