### ISSUE TITLE
Only for 64 bit?

### ISSUE THREAD

**Issue by osjasmine** [jroddev/android-oss-release-tracker#4]
On my phone it gives me parsing error. My phone is 32 bit, Android 10. So I guess it either doesnt support 32 bit or android 10.

**Comment by jroddev** [comment]
@osjasmine Try version `0.1.3` https://github.com/jroddev/android-oss-release-tracker/releases/tag/0.1.3
I have reduced the minSdk version from 30 to 29 to support Android 10 and everything seems to work.
So far only tested in an emulator so it would be good to get confirmation on an actual device.

**Comment by osjasmine** [comment]
Thanks the latest version installed with no problems.
