### ISSUE TITLE
[Feature request] export app list

### ISSUE THREAD

**Issue by ippocratis** [jroddev/android-oss-release-tracker#8]
An option to export the added apps list for easy import across installs would make sense. 
I have like 20-30 apps I want to monitor and its a load to manualy re-import their repo on an app reinstall,  rom change, factory reset etc.
Thanks

**Comment by jroddev** [comment]
@ippocratis I'm hoping to add this functionality soon. 
Just so you know, your use-case will likely be affected by this issue
https://github.com/jroddev/android-oss-release-tracker/issues/5
20 apps is about the most we can get currently before hitting GitHub API rate-limiting for anonymous users.

**Comment by jroddev** [comment]
@ippocratis 

Import / Export added in [0.1.4](https://github.com/jroddev/android-oss-release-tracker/releases/tag/0.1.4)
You can also use it to bulk import all of your apps as it's just a text file with one url per line.
