### ISSUE TITLE
Add other Git websites

### ISSUE THREAD

**Issue by m3thm4th** [jroddev/android-oss-release-tracker#9]
Add other Git websites like [Codeberg](https://codeberg.org/), [Bitbucket](https://bitbucket.org/), [Sourcehut](https://sr.ht/), [Launchpad](https://launchpad.net/), [NotABug](https://notabug.org/), [SourceForge](https://sourceforge.net/)

**Comment by jroddev** [comment]
@m3thm4th how would you order these in terms of a priority?
Do you have links to sample projects in each to use for reference/testing?

I'm also happy to review PRs if anyone wants to add implementations themselves.

The [Repo](https://github.com/jroddev/android-oss-release-tracker/blob/master/app/src/main/java/com/jroddev/android_oss_release_tracker/repo/Repo.kt) type will need to be implemented.
```
    fun getOrgName(repoUrl: String): String
    fun getApplicationName(repoUrl: String): String
    fun getIconUrl(repoUrl: String, branch: String, androidRoot: String): String
    fun getUrlOfRawFile(org: String, app: String, branch: String, filepath: String): String
    suspend fun fetchBranchName(org: String, app: String, requestQueue: RequestQueue): Either<String, Error>
    suspend fun fetchLatestVersion(org: String, app: String, requestQueue: RequestQueue): Either<LatestVersionData, Error>
    suspend fun tryDetermineAndroidRoot(org: String, app: String, branch: String, requestQueue: RequestQueue): String
```

There is a CommonRepo abstract base class to help with some common parsing tasks.
The project also has some [coroutine based http wrappers](https://github.com/jroddev/android-oss-release-tracker/blob/master/app/src/main/java/com/jroddev/android_oss_release_tracker/repo/ApiUtils.kt) to simplify async request code.

**Comment by m3thm4th** [comment]
I don't know. I would probably see Codeberg as more important in that it's often preferred to GitHub or GitLab and the others as nice to have, I can't think of projects on any of them at the moment. I just like the idea of this app, I would like to have it on desktop too, if I remember about projects on any of them I will inform you.

**Comment by IzzySoft** [comment]
@jroddev at the moment we struggle with adding the NonFreeNet anti-feature ([F-Droid inclusion](https://gitlab.com/fdroid/fdroiddata/-/merge_requests/12125#note_1186714418)). If you could at least include self-hosted GitLab (just needs replacing the hostname), that would already help the decision against that.

I'd suggest we add your app **with** NonFreeNet for now and you drop us a note once a free service (self-hosted GitLab, or Codeberg/Gitea) is supported so we remove it again?

**Comment by jroddev** [comment]
At the moment I use the hostname to determine whether to use GitHub or GitLab implementation.
If there's a way to auto-detect what is being used (through api call perhaps?) then self-hosted GitLab should be trivial to add. 

At the moment only the url you provide is saved, everything else is calculated on the fly. I plan to save other fields in future to reduce the number of API calls and allow overriding when my detection logic fails. A dropdown to select the resolver (github, gitlab, etc, etc) could be added.

**Comment by IzzySoft** [comment]
> If there's a way to auto-detect what is being used

Not that I know of. But for starters, a passable logic could be: If it's neither `github.com` nor `gitlab.com` but carries the term `gitlab` in its host name, it's most likely a self-hostet GitLab (to my experience, about 90% of those self-hosted GitLabs have the term "gitlab" in their host name). Not perfect, but already an improvement.

> At the moment only the url you provide is saved

In the future, you could also save the determined/specified service and, unless auto-detected, prompt the user for a list of services supported to choose from (don't allow to save if no working variant was found of course).

> A dropdown to select the resolver (github, gitlab, etc, etc) could be added.

Excactly. And where absolutely clear (e.g. `github.com`, `gitlab.com` and `codeberg.org`/`gitea.io`) either have the proper service pre-selected or, if absolutely sure, just skip the popup.

That said: Do you prefer us to apply NonFreeNet now and merge the MR to have your app listed (removing NonFreeNet once we can) – or rather want us to wait until that anti-feature is no longer needed? IMHO the first step (identifying self-hosted GitLab by the term `gitlab` in its hostname and allow saving that when the API call succeeded) would be sufficient to not needing the anti-feature.

**Comment by IzzySoft** [comment]
To get things done, I will go now to merge it with the AF still active. Please give us a ping when we can remove it (e.g. when self-hosted GitLab is supported at least if it can be "identified" by the host name). Thanks!

**Comment by jroddev** [comment]
@IzzySoft sorry for the delay - life. 

Now in [0.1.5](https://github.com/jroddev/android-oss-release-tracker/releases/tag/0.1.5) I am just making the assumption that if it doesn't contain the word "github" in the URL that it should use the GitLab resolver. Naive - yes, but gives us self-hosted GitLab support until I do some proper refactoring. 
Looking for the phrase "gitlab" is the logic I had previously, but I have seen some self-hosted GitLab instances use `git.<company>.com` instead of explicitly mentioning GitLab.

before
```
if (repoUrl.contains("github")) {
  GitHub()
} else if (repoUrl.contains("gitlab")) {
  GitLab()
} else {
  null
}
```
after
```
if (repoUrl.contains("github")) {
  GitHub()
} else {
  GitLab()
}
```

**Comment by IzzySoft** [comment]
> sorry for the delay - life

No need to apologize. I just wanted to get the task done, and we can fix up anytime.

> I am just making the assumption that if it doesn't contain the word "github" in the URL

I'd restrict that to the host name, not the full URL. Imagine I'd have a repo at `https://gitlab.example.com/funnybear/github-faker`, I'd totally fool your logic. Cannot fool it that easy if you restrict the filter to the host name (gee, yes, `github.mydomain.com`, but meh).

You could also consider making that a `case` statement, to be prepared for gitea/codeberg with a future version :wink: Apart from that: Yes, that was what I had in mind. Please let me know once that's up at F-Droid, and I'll take care for removing the AF (you could also watch the [build monitor](https://monitor.f-droid.org/builds/running) – once it's in there, the corresponding build section exists and I can edit/update the YAML so it's part of the next cycle already, if you want to speed it up a few days :see_no_evil:). Thanks a lot!

**Comment by m3thm4th** [comment]
Maybe a solution could be to see if it matches a hostname and if it doesn't, or it's a custom one, give the user a multiple selection option

**Comment by IzzySoft** [comment]
@m3thm4th that will definitely make sense as soon as support for Gitea is added. For now, the above approach should be fine: it's either `github.com`, `gitlab.com` or a self-hosted GitLab instance – all else is not yet supported. And there is no such thing as a self-hosted Github :wink:

**Comment by jroddev** [comment]
Closing this issue for now. Once I have added the ability to override what is auto-detected then gitea, etc will become viable.
